### PR TITLE
Add casadi port

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
cc @traversaro

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
The CI fails with the following error
```
CMake Error at D:/a/robotology-vcpkg-binary-ports/robotology-vcpkg-binary-ports/casadi/portfile.cmake:35 (vcpkg_fixup_pkgconfig):
  Unknown CMake command "vcpkg_fixup_pkgconfig".
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)
```

That's strange because `vcpkg_fixup_pkgconfig` is defined from vcpkg: https://vcpkg.readthedocs.io/en/latest/maintainers/vcpkg_fixup_pkgconfig/

**Comment by traversaro** [comment]
The CI is using some old versions of vcpkg due to the bug https://github.com/microsoft/vcpkg/issues/10119, but that has been fixed since then so we can bump the version of vcpkg tested in CI.

**Comment by GiulioRomualdi** [comment]
> The CI is using some old versions of vcpkg due to the bug [microsoft/vcpkg#10119](https://github.com/microsoft/vcpkg/issues/10119), but that has been fixed since then so we can bump the version of vcpkg tested in CI.

I see, unfortunately, the latest release [`2020.07`](https://github.com/microsoft/vcpkg/releases/tag/2020.07) does not contain the fix https://github.com/microsoft/vcpkg/pull/13231

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks!

**Pull request merged**
